language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xialeistudio"
  - git config user.email "xialeistudio.github.io"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - curl --connect-timeout 20 --max-time 30 -s ${WEBHOOK_ENDPOINT}

branches:
  only:
    - hexo