baseURL: 'https://www.ddhigh.com'
title: 每天进步一点点
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
homepage: 'https://www.ddhigh.com'
defaultContentLanguage: 'zh'
paginate: 10
summaryLength: 5


taxonomies:
  category: categories
  series: series
  tag: tags
permalinks:
  page:
    posts: /:year/:month/:day/:slug
outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
    notAlternative: true
sitemap:
  changeFreq: ""
  filename: sitemap.xml
  priority: 0.5

params:
  brand: DayDayUP
  avatarURL: /img/mp.png
  author: Lei Xia
  authorDescription: Sr. Software Engineer | Solution Architect
  info: |
    Writing code, Enjoying life, Building future
    
    [RSS](/en/atom.xml) ·
    [Sponsor](/en/sponsors)
  keywords: 
    - Web
    - Java
    - Go
    - Node.js
    - PHP
    - Koa
    - MySQL
    - Redis
    - front-end
    - back-end
    - database
  description: Welcome to my blog! Articles related to web development are provided here, covering technologies such as Java, Go, Node.js, PHP, Koa, MySQL, and Redis. From front-end to back-end, providing you with practical guidance and advice on web application development. Explore best practices and learn about RESTful API design, responsive web design, and performance and security.
  favicon: /img/favicon.ico
  sponsors:
    buymeacoffee:
      enable: true
      url: https://www.buymeacoffee.com/leixia
      buttom_api: https://img.buymeacoffee.com/button-api/?text=Buy%20me%20a%20coffee&emoji=&slug=iguangzhengli&button_colour=FFDD00&font_colour=000000&font_family=Cookie&outline_colour=000000&coffee_colour=ffffff
      qr: /img/bmc_qr.png
    # wechat:
    #   enable: true
    #   qr: /img/wx_qr.png
    # alipay:
    #   enable: true
    #   qr: /img/alipay_qr.png
  mermaid:
    enable: true
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
  darkModeTheme: data-dark-mode
  comments:
    giscus:
      enable: true
      repo: xialeistudio/discussion
      repo_id: R_kgDOKurTRA
      category: General
      category_id: DIC_kwDOKurTRM4CbCJt
      mapping: pathname
      position: bottom
      lang: en # pick a language from https://github.com/giscus/giscus/tree/main/locales
  analytics:
    google:
      # SiteVerificationTag: xxx
    umami:
      enable: true
      website_id: 52f8f0f9-d93d-466b-8ef5-508aae8c4ed4
      url: https://analysis.ddhigh.com/script.js
  guestbook:
    title: Guestbook
    description: Leave a comment below. It could be anything –- question, appreciation, information, or even humor.
  social:
    - name: GitHub
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/xialeistudio'
  books:
    - title: ThinkPHP5实战
      link: http://www.tup.tsinghua.edu.cn/booksCenter/book_08079501.html
      pubdate: 2019.10
      isbn: 9787302533580

    - title: ThinkPHP实战
      link: http://www.tup.tsinghua.edu.cn/booksCenter/book_06867701.html
      pubdate: 2017.04
      isbn: 9787302466529

    - title: Node.js+Webpack 开发实战
      link: http://www.tup.tsinghua.edu.cn/booksCenter/book_07638401.html
      pubdate: 2020.08
      isbn: 9787302555957
languages:
  en:
    contentDir: content/en
    languageName: EN
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Archives
          url: /archives
          weight: 2
        - name: Books
          url: /books
          weight: 4
        - name: Guestbook
          url: /guestbook
          weight: 5
    params:
      books:
      - title: ThinkPHP5 in action
        link: http://www.tup.tsinghua.edu.cn/booksCenter/book_08079501.html
        pubdate: 2019.10
        isbn: 9787302533580

      - title: ThinkPHP in action
        link: http://www.tup.tsinghua.edu.cn/booksCenter/book_06867701.html
        pubdate: 2017.04
        isbn: 9787302466529

      - title: Node.js & Webpack in action
        link: http://www.tup.tsinghua.edu.cn/booksCenter/book_07638401.html
        pubdate: 2020.08
        isbn: 9787302555957
  zh:
    contentDir: content/zh
    languageName: 中
    author: Lei Xia
    menu:
      main:
        - name: 首页
          url: /
          weight: 1
        - name: 归档
          url: /archives
          weight: 2
        - name: 出版物
          url: /books
          weight: 4
        - name: 留言板
          url: /guestbook
          weight: 5
    params:
      brand: 每天进步一点点
      authorDescription: Sr. Software Engineer | Solution Architect
      keywords: 
        - Web开发
        - Java
        - Go
        - Node.js
        - PHP
        - Koa
        - MySQL
        - Redis
        - 前端
        - 后端
        - 数据库
      description: 欢迎来到我的博客！这里提供与Web开发相关的文章，涵盖Java、Go、Node.js、PHP、Koa、MySQL和Redis等技术。从前端到后端，为您提供有关Web应用程序开发的实用指南和建议。探索最佳实践，了解RESTful API设计、响应式网页设计以及性能和安全性方面的知识。
      info:  | 
        抒写代码，尽享生活，筑就未来。
        
        [订阅](/atom.xml) ·
        [赞赏](/sponsors)
      guestbook:
        title: 留言板
        description: 您的评论，会让该网站更精彩！
      books:
      - title: ThinkPHP5实战
        link: http://www.tup.tsinghua.edu.cn/booksCenter/book_08079501.html
        pubdate: 2019.10
        isbn: 9787302533580

      - title: ThinkPHP实战
        link: http://www.tup.tsinghua.edu.cn/booksCenter/book_06867701.html
        pubdate: 2017.04
        isbn: 9787302466529

      - title: Node.js & Webpack实战
        link: http://www.tup.tsinghua.edu.cn/booksCenter/book_07638401.html
        pubdate: 2020.08
        isbn: 9787302555957
      sponsors:
        buymeacoffee:
          enable: false
        wechat:
          enable: true
          qr: /img/wx_qr.png
        alipay:
          enable: true
          qr: /img/alipay_qr.png