name: Deploy
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn run publish
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY }}
          publish_dir: ./public
          publish_branch: gh-pages
          
      - name: Archive Github Page
        run: tar cvzf public.tgz public

      - name: Deploy Server
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} >> private_key.pem
          scp -i private_key.pem  public.tgz root@ww.ddhigh.com:/var/www/public.tgz
          ssh -i private_key.pem "cd /var/www && tar xzf public.tgz && mv public test && chown -R www-data:www-data test"