name: Deploy
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn run publish

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY }}
          publish_dir: ./public
          publish_branch: gh-pages

      - name: Deploy Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: 'www.ddhigh.com'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './public/*'
          remote_path: '/var/www/test'
          args: '-o ConnectTimeout=5'
  